# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.2
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "poetry.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -U pip poetry
            poetry install
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "poetry.lock" }}
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest --cov neural_semigroups --cov-report html --cov-fail-under=85\
                   --junit-xml test-results/neural-semigroups.xml\
                   tests/
            mkdir -p build
            mv htmlcov build/htmlcov
      - run:
          name: run linters
          command: |
            . venv/bin/activate
            pycodestyle --max-doc-length 160 --ignore E501,W504\
                        neural_semigroups scripts tests
            pylint --rcfile=.pylintrc neural_semigroups scripts
      - run:
          name: run type checks
          command: |
            . venv/bin/activate
            mypy --config-file mypy.ini neural_semigroups scripts tests
      - run:
          name: building documentation
          command: |
            . venv/bin/activate
            cd doc
            make clean html
            mv build/html ../build/htmldoc
      - store_artifacts:
          path: build
      - store_test_results:
          path: test-results
